/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2Nhcmxvc3JhbmdlbC9EZXNrdG9wL1Byb2plY3RzL0VkdWNhdGlvbi9Bbmd1bGFyL1VkZW15L0RlcGxveW1lbnQvZGVwbG95LWRlbW8vc3JjL2FwcC9uYXZiYXIvbmF2YmFyLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvY2FybG9zcmFuZ2VsL0Rlc2t0b3AvUHJvamVjdHMvRWR1Y2F0aW9uL0FuZ3VsYXIvVWRlbXkvRGVwbG95bWVudC9kZXBsb3ktZGVtby9zcmMvYXBwL25hdmJhci9uYXZiYXIuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
