/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.media[_ngcontent-%COMP%] { \n    margin-bottom: 30px;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2Nhcmxvc3JhbmdlbC9EZXNrdG9wL1Byb2plY3RzL0VkdWNhdGlvbi9Bbmd1bGFyL1VkZW15L0RlcGxveW1lbnQvZGVwbG95LWRlbW8vc3JjL2FwcC9naXRodWItZm9sbG93ZXJzL2dpdGh1Yi1mb2xsb3dlcnMuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9jYXJsb3NyYW5nZWwvRGVza3RvcC9Qcm9qZWN0cy9FZHVjYXRpb24vQW5ndWxhci9VZGVteS9EZXBsb3ltZW50L2RlcGxveS1kZW1vL3NyYy9hcHAvZ2l0aHViLWZvbGxvd2Vycy9naXRodWItZm9sbG93ZXJzLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
